__author__ = "Paul Schifferer <paul@schifferers.net>"
"""
constants.py
- Contstants for keys and environment variable names
"""

CLIENT_AUTH_TOKEN = 'CLIENT_AUTH_TOKEN'

SENTRY_DSN = 'SENTRY_DSN'
SENTRY_ENV = 'SENTRY_ENV'

APPLICATION_NAME = "statesman"
PROFILE_KEY = 'profile'
JWT_PAYLOAD = 'jwt_payload'
CURRENT_USER_ID = 'current_user_id'
SERVERS_FILE = 'SERVERS_FILE'
SERVERS = 'servers'

SLACK_SIGNATURE_VERSION = 'v0'
SLACK_SIGNING_SECRET_ENV = 'SLACK_SIGNING_SECRET'
SLACK_VERIFICATION_TOKEN_ENV = 'SLACK_VERIFICATION_TOKEN'

# configuration
SEGMENT_WRITE_KEY = "SEGMENT_WRITE_KEY"
DEBUG = "DEBUG"
PORT = "PORT"
LOG_LEVEL = "LOG_LEVEL"
DB_HOST = "DB_HOST"
DB_PORT = "DB_PORT"
DB_USER = "DB_USER"
DB_PW = "DB_PW"
DB_NAME = "DB_NAME"
DB_OPTS = "DB_OPTS"
REDIS_HOST = "REDIS_HOST"
REDIS_PORT = "REDIS_PORT"
REDIS_DB = "REDIS_DB"
REDIS_PW = "REDIS_PW"
LOGSTASH_HOST = "LOGSTASH_HOST"
LOGSTASH_DB_PATH = "LOGSTASH_DB_PATH"
LOGSTASH_TRANSPORT = "LOGSTASH_TRANSPORT"
LOGSTASH_PORT = "LOGSTASH_PORT"
SECRET_KEY = "SECRET_KEY"
CSRF_TOKEN = "CSRF_TOKEN"
SESSION_TYPE = "SESSION_TYPE"
BUILD_INFO_PATH = "BUILD_INFO_PATH"
