__author__ = "Paul Schifferer <paul@schifferers.net>"
"""
"""


# FLAG_TRACKED_ENCOUNTER = 'tracked'
# FLAG_REMOVED = 'removed'


# ENUM_ORDERING_HIGH_TO_LOW = 'high-to-low'
# ENUM_ORDERING_LOW_TO_HIGH = 'low-to-high'
# ENUM_ORDERING_PCVADVERSARY = 'pc-v-adversary'
# ENUM_ORDERING_PLAYER_MANAGED = 'player-managed'


ROLE_ADMIN = 'admin'
ROLE_USER = 'user'


PERMISSION_READ = 'read'
PERMISSION_WRITE = 'write'
PERMISSION_BLOCK = 'block'

PERMISSION_OP_READ = PERMISSION_READ
PERMISSION_OP_WRITE = PERMISSION_WRITE
PERMISSION_OP_BLOCK = PERMISSION_BLOCK
PERMISSION_OP_REMOVE = 'remove'

PERMISSION_THING_COLLECTION = 'collection'
PERMISSION_THING_ITEM = 'item'

PERMISSION_NAME_ALL = '__all__'
PERMISSION_NAME_DEFAULT = '__default__'

OPERATOR_SYMBOL_ADD = '+'
OPERATOR_SYMBOL_SUBTRACT = '-'
OPERATOR_SYMBOL_MULTIPLY = '*'
OPERATOR_SYMBOL_DIVIDE = '/'

ADJUST_OP_ADD = 'add'
ADJUST_OP_SUBTRACT = 'subtract'
ADJUST_OP_MULTIPLY = 'multiply'
ADJUST_OP_DIVIDE = 'divide'
