__author__ = "Paul Schifferer <paul@schifferers.net>"
"""
constants.py
- Contstants for keys and environment variable names
"""

SENTRY_DSN = 'SENTRY_DSN'
SENTRY_ENV = 'SENTRY_ENV'

APPLICATION_NAME = "statesman"

SLACK_SIGNATURE_VERSION = 'v0'
SLACK_SIGNING_SECRET_ENV = 'SLACK_SIGNING_SECRET'
SLACK_VERIFICATION_TOKEN_ENV = 'SLACK_VERIFICATION_TOKEN'

SLACK_SIGNATURE_HEADER_KEY = 'X-Slack-Signature'
SLACK_TIMESTAMP_HEADER_KEY = 'X-Slack-Request-Timestamp'

DISCORD_RELAY_SIGNATURE_VERSION = 'v1'
DISCORD_RELAY_NONCE_HEADER_KEY = 'X-Statesman-Relay-Nonce'
DISCORD_RELAY_SIGNATURE_HEADER_KEY = 'X-Statesman-Relay-Signature'
DISCORD_RELAY_SIGNING_SECRET_ENV = 'DISCORD_RELAY_SIGNING_SECRET'

ITEM_SEPARATOR = '|'
